update chart

diff --git a/kafka-connect/templates/configmap-connect.yaml b/kafka-connect/templates/configmap-connect.yaml
--- a/kafka-connect/templates/configmap-connect.yaml
+++ b/kafka-connect/templates/configmap-connect.yaml
@@ -29,7 +29,7 @@ data:
     echo "Current sink file: ${sink_file}"
     ls -la ${sink_file}
 
-    timeout -s HUP {{ .Values.restartTimeout }} /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/custConfig/connect-standalone.properties /opt/bitnami/kafka/custConfig/connect-file-sink.properties
+    timeout -s HUP {{ .Values.restartTimeout }} /opt/bitnami/kafka/bin/connect-standalone.sh /etc/connectConfig/connect-standalone.properties /etc/connectConfig/connect-file-sink.properties
 
     # exit code 124 indicates that timeout timed out
     exit_code=$?
@@ -55,6 +55,72 @@ data:
 
     ls -la ${sink_file}
     rm ${sink_link}
+
+  restore.sh: |-
+
+    # sh /opt/bitnami/kafka/filesink/restore.sh
+    # restore_topic=connect1
+    # restore_files=/opt/bitnami/kafka/filesink/snapshot/connect*.sink
+    # kafka_server=kafka
+    # restore_from_time="2021-01-19T15:57"
+    params=$#
+    if [ "$#" -ne 4 ]; then
+        echo "Illegal number of parameters: required: 4, supplied: $params"
+        echo
+        echo "Usage $0 restore_topic kafka_server \"restore_files\"  \"restore_from_time\""
+        echo
+        echo "restore_topic: destination topic to restore to"
+        echo "kafka_server: kafka server"
+        echo "restore_files: path to the files to restore from, example \"/opt/bitnami/kafka/filesink/connect*.sink\" - must be in quotes"
+        echo "restore_from_time: timestamp to restore from, example \"2021-01-19T15:57\" - must be in quotes"
+        echo
+        echo "Example:"
+        echo
+        echo "sh /opt/bitnami/kafka/filesink/restore.sh connect1 kafka \"/opt/bitnami/kafka/filesink/snapshot/connect*.sink\"  \"2021-01-19T15:57\""
+
+        exit
+    fi
+
+    restore_topic=$1
+    kafka_server=$2
+    restore_files=$3
+    restore_from_time=$4
+
+    printf "\033c"
+
+    echo "Restoring topic: $restore_topic"
+    echo "Kafka server: $kafka_server"
+    echo
+    echo "Restoring from: $restore_files"
+    ls $restore_files
+    echo
+    echo "Restoring from timestamp: $restore_from_time"
+
+    #check if the files are readable
+    for file in $restore_files
+      do
+        test -f $file  || { echo "File $file does not exist" ; exit ; }
+        echo $file
+      done
+
+    restore_source="/tmp/restoredata.$(date +%s)"
+    touch $restore_source || { echo "Cant touch file: $restore_source" ; exit ; }
+    test -w $restore_source || { echo "File $restore_source does not exist" ; exit ; }
+
+
+    cat $restore_files | awk -F'utcTime":"|"}}' '$2 >= "'$restore_from_time'"' > $restore_source
+
+    read -p "Continue (yes/no)?" choice
+    case "$choice" in
+      yes ) echo "Executing restore...";;
+      * )
+        echo "Exiting."
+        exit
+      ;;
+    esac
+
+    kafka-console-producer.sh --broker-list $kafka_server:9092 --topic $restore_topic < $restore_source
+
 
   connect-standalone.properties: |-
     bootstrap.servers={{ .Values.kafkaSvcName }}.{{ .Values.kafkaSvcNamespace }}.svc.cluster.local:9092
